spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            security-manager:
              - host: localhost
                port: 8001
              - host: localhost
                port: 8002
              - host: localhost
                port: 8003
logging:
  level:
    root: INFO
    org.pluto.clientmachine: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
  file:
    name: /home/kris/IdeaProjects/logs/${app.name}-${server.port}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"